name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Debug Secret Length
        run: echo "${{ secrets.YOUR_KEYSTORE_PASSWORD }}" | wc -c

      - name: Load Google Services File
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.YOUR_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Set up keystore for signing
        run: |
          mkdir -p $HOME/.android
          mv keystore.jks $HOME/.android/keystore.jks

      - name: Build and sign APK with Gradle
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.YOUR_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.YOUR_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          HA_GITHUB_TOKEN: ${{ secrets.HA_GITHUB_TOKEN }}
          HA1_VERSION_SOURCE: 'ci'

      - name: Upload APK Zip
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ github.sha }}
          path: app/build/outputs/apk/release/Han1meViewer-v*.apk
